{"uid":"809dd6c6402764c4","name":"test_user_lifecycle","fullName":"tests.test_integration_workflow#test_user_lifecycle","historyId":"d5c169c8bfd17c6f39446f28f192f1bc","time":{"start":1760526662933,"stop":1760526662946,"duration":13},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"user_payload","time":{"start":1760526662933,"stop":1760526662933,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"attachmentStep":false,"hasContent":false},{"name":"client","time":{"start":1760526662933,"stop":1760526662933,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"attachmentStep":false,"hasContent":false}],"testStage":{"status":"passed","steps":[],"attachments":[{"uid":"a5d35355103a3654","name":"log","source":"a5d35355103a3654.txt","type":"text/plain","size":780},{"uid":"8f49dc6bdafd0785","name":"stderr","source":"8f49dc6bdafd0785.txt","type":"text/plain","size":782}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":2,"attachmentStep":false,"hasContent":true},"afterStages":[],"labels":[{"name":"story","value":"User lifecycle flow: POST → GET → DELETE"},{"name":"feature","value":"Integration API"},{"name":"tag","value":"api"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_integration_workflow"},{"name":"host","value":"MacBook-Air.local"},{"name":"thread","value":"55889-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_integration_workflow"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"53a2f9a6b1c0b74d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/users (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103a6c7c0>: Failed to establish a new connection: [Errno 61] Connection refused'))","time":{"start":1760524920920,"stop":1760524920928,"duration":8}}],"categories":[],"tags":["api"]},"source":"809dd6c6402764c4.json","parameterValues":[]}